module Docscribe
  module Types
    module Sorbet
      class BaseProvider
        @collapse_generics: bool

        @collapse_object_generics: bool

        @index: Hash[ [ String, Symbol, Symbol ], Types::MethodSignature ]

        @warned: bool

        def initialize: (?collapse_generics: bool, ?collapse_object_generics: bool) -> void

        def signature_for: (container: String, scope: Symbol, name: (Symbol | String)) -> (Types::MethodSignature | nil)

        private

        def load_from_string: (String source, label: String) -> void

        def parse: (::RBS::Prototype::RBI parser, String source) -> void

        def suppress_rbs_noise: [T] () { () -> T } -> T

        def index_decls: (Array[untyped] decls) -> void

        def process_method_member: (String container, untyped member) -> void

        def method_definition_member?: (untyped member) -> (bool | nil)

        def build_signature: (::RBS::Types::Function func) -> Types::MethodSignature

        def build_param_types: (::RBS::Types::Function func) -> Hash[String, String]

        def add_keywords!: (Hash[String, String] param_types, Hash[Symbol, ::RBS::Types::Function::Param] keywords) -> void

        def add_positionals!: (Hash[String, String] param_types, Array[::RBS::Types::Function::Param] list) -> void

        def build_rest_positional: (::RBS::Types::Function func) -> (Types::RestPositional | nil)

        def build_rest_keywords: (::RBS::Types::Function func) -> (Types::RestKeywords | nil)

        def format_type: (Docscribe::Types::RBS::TypeFormatter::rbs_type type) -> String

        def normalize_container: (String name) -> String

        def warn_once: (String msg) -> void
      end
    end
  end
end
