inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-sorted_methods_by_call
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - sig/**/*
    - vendor/**/*
    - .gem_rbs_collection/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/DoubleNegation:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/CommentIndentation:
  AllowForAlignment: true

