module Docscribe
  module CLI
    interface _Subcommand
      def run: (Array[String]) -> Integer
    end

    COMMANDS: Hash[String, Symbol]

    SUBCOMMAND_FILES: Hash[String, String]

    def self.run: (Array[String] argv) -> Integer

    private

    def self.subcommand?: (String? cmd) -> bool

    def self.dispatch_subcommand: (Array[String] argv) -> Integer
  end
end

