module Docscribe
  class Config
    @rbs_provider: (Types::RBS::Provider | nil)

    @core_rbs_provider: (Types::RBS::Provider | nil)

    @rbs_warning_emitted: bool

    def rbs_provider: () -> (Types::RBS::Provider | nil)

    def rbs_enabled?: () -> bool

    def core_rbs_provider: () -> (Types::RBS::Provider | nil)

    def rbs_warn_missing_collection?: () -> bool

    private

    def ruby_supports_rbs?: () -> bool

    def build_rbs_provider: () -> (Types::RBS::Provider | nil)

    def build_core_rbs_provider: () -> (Types::RBS::Provider | nil)

    def rbs_sig_dirs: () -> Array[String]

      def rbs_collection_dirs: () -> Array[String]

      def discovered_collection_dir: () -> (String | nil)

    def rbs_collapse_generics?: () -> bool

    def rbs_collapse_object_generics?: () -> bool
  end
end
