module Docscribe
  module CLI
    module ConfigBuilder
      def self?.build: (Config base, Hash[Symbol, untyped] options) -> Config

      def self?.needs_override?: (Hash[Symbol, untyped] options) -> bool

      def self?.filter_overrides?: (Hash[Symbol, untyped] options) -> bool

      def self?.rbs_overrides?: (Hash[Symbol, untyped] options) -> bool

      def self?.sorbet_overrides?: (Hash[Symbol, untyped] options) -> bool

      def self?.apply_filter_overrides: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.apply_method_filters: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.apply_file_filters: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.apply_rbs_overrides: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.apply_rbs_collection: (Hash[String, untyped] raw) -> void

      def self?.apply_sorbet_overrides: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.output_overrides?: (Hash[Symbol, untyped] options) -> bool

      def self?.apply_output_overrides: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.validation_overrides?: (Hash[Symbol, untyped] options) -> bool

      def self?.apply_validation_overrides: (Hash[String, untyped] raw, Hash[Symbol, untyped] options) -> void

      def self?.warn_missing_rbs_collection: (Config conf, Hash[Symbol, untyped] options) -> void
    end
  end
end
