module Docscribe
  module CLI
    module Options
      DEFAULT: { stdin: false, mode: :check, strategy: :safe, verbose: false, explain: false, quiet: false, format: :text, config: nil, include: Array[String], exclude: Array[String], include_file: Array[String], exclude_file: Array[String], rbs: false, sig_dirs: Array[String], sorbet: false, rbi_dirs: Array[String], rbs_collection: false, keep_descriptions: false, no_boilerplate: false, progress: false, parallel: false, server: false, validate_types: false }

      BANNER: String

      def self?.parse!: (Array[String] argv) -> Formatters::opts

      def self?.build_option_parser: (Hash[Symbol, untyped] options, Hash[Symbol, (Symbol | nil)] autocorrect) -> OptionParser

      def self?.define_autocorrect_options: (OptionParser opts, Hash[Symbol, (Symbol | nil)] autocorrect) -> void

      def self?.define_input_options: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_stdin_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_config_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_server_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_type_options: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_rbs_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_sig_dir_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_sorbet_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_rbi_dir_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_rbs_collection_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_validate_types_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_filter_options: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_include_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_exclude_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_include_file_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_exclude_file_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_output_options: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_verbose_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_progress_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_parallel_option: (OptionParser parser, Hash[Symbol, untyped] opts) -> void

      def self?.define_explain_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_quiet_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_format_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_keep_descriptions_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_no_boilerplate_option: (OptionParser opts, Hash[Symbol, untyped] options) -> void

      def self?.define_misc_options: (OptionParser opts) -> void

      def self?.resolve_mode_and_strategy!: (Hash[Symbol, untyped] options, (Symbol | nil) autocorrect_mode) -> void

      def self?.route_include_exclude: (Hash[Symbol, untyped] options, (:include | :exclude) kind, String value) -> void

      def self?.looks_like_file_pattern?: (String pat) -> bool
    end
  end
end
