module Docscribe
  module Types
    module Primitive
      def self.primitive?: (String token) -> bool
      def primitive?: (String token) -> bool

      def self.core_primitives: () -> Array[String]
      def core_primitives: () -> Array[String]

      def self.load_core_primitives: () -> Array[String]
      def load_core_primitives: () -> Array[String]

      def self.alias_token?: (String token) -> bool
      def alias_token?: (String token) -> bool

      def self.alias_pattern?: (String token) -> bool
      def alias_pattern?: (String token) -> bool

      def self.alias_type?: (String type_str) -> bool
      def alias_type?: (String type_str) -> bool
    end
  end
end
