module Docscribe
  module Types
    module Primitive
      def self.primitive?: (String token) -> bool
      def primitive?: (String token) -> bool

      def self.core_primitives: () -> Array[String]
      def core_primitives: () -> Array[String]

      def self.load_core_primitives: () -> Array[String]
      def load_core_primitives: () -> Array[String]

      def self.load_yard_primitives: (Set[String] primitives) -> Set[String]
      def load_yard_primitives: (Set[String] primitives) -> Set[String]

      def self.load_rbs_core: (Set[String] primitives) -> Set[String]
      def load_rbs_core: (Set[String] primitives) -> Set[String]

      def self.merge_primitives: (Set[String] primitives) -> Set[String]
      def merge_primitives: (Set[String] primitives) -> Set[String]

      def self.alias_token?: (String token) -> bool
      def alias_token?: (String token) -> bool

      def self.alias_pattern?: (String token) -> bool
      def alias_pattern?: (String token) -> bool

      def self.alias_type?: (String type_str) -> bool
      def alias_type?: (String type_str) -> bool

      def self.normalized_base: (String token) -> String
      def normalized_base: (String token) -> String

      def self.populate_class_decls: (RBS::Environment env, Set[String] primitives) -> void
      def populate_class_decls: (RBS::Environment env, Set[String] primitives) -> void

      def self.populate_interface_decls: (RBS::Environment env, Set[String] primitives) -> void
      def populate_interface_decls: (RBS::Environment env, Set[String] primitives) -> void
    end
  end
end
